{% set name = "lm-format-enforcer" %}
{% set version = "0.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lm_format_enforcer-{{ version }}.tar.gz
  sha256: 3e0bfeaf9fac9f69c8947da554db9a19a76d0be6e85075055f2c70d0aca420da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - poetry-core
    - pip
    - wheel
  run:
    - python
    - pydantic
    - interegular
    - packaging
    - pyyaml

test:
  imports:
    - lmformatenforcer
  commands:
    - pip check
  requires:
    - pip
    - numpy
    - python

about:
  home: https://github.com/noamgat/lm-format-enforcer
  summary: Enforce the output format (JSON Schema, Regex etc) of a language model
  license: MIT
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - rxm7706
