{% set name = "lm-format-enforcer" %}
{% set version = "0.10.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lm_format_enforcer-{{ version }}.tar.gz
  sha256: 130bd7ce8a6b224f25b6314ba9ae78ee4b48594db1767c74391c9182e2902a6c

build:
  skip: true # [ py<310 ]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - poetry-core >=1.1.0
    - pip
  run:
    - python
    - pydantic >=1.10.8
    - interegular >=0.3.2
    - packaging
    - pyyaml

test:
  imports:
    - lmformatenforcer
  commands:
    - pip check
  requires:
    - pip
    - numpy >=1.21.0
    - python

about:
  home: https://github.com/noamgat/lm-format-enforcer
  summary: Enforce the output format (JSON Schema, Regex etc) of a language model
  description: |
    Language models are able to generate text, but when requiring a precise
    output format, they do not always perform as instructed. Various prompt
    engineering techniques have been introduced to improve the robustness of
    the generated text, but they are not always sufficient. This project solves
    the issues by filtering the tokens that the language model is allowed to
    generate at every timestep, thus ensuring that the output format is
    respected, while minimizing the limitations on the language model.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/noamgat/lm-format-enforcer
  dev_url: https://github.com/noamgat/lm-format-enforcer

extra:
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - rxm7706
